DotNetFlicks.Web/Controllers/DepartmentController.cs
using DotNetFlicks.Common.Models;
using DotNetFlicks.Managers.Interfaces;
using DotNetFlicks.ViewModels.Department;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DotNetFlicks.Web.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private IDepartmentManager _departmentManager;

        public DepartmentController(IDepartmentManager departmentManager)
        {
            _departmentManager = departmentManager;
        }

        public ActionResult Index(string sortOrder, string search, int? pageIndex, int? pageSize)
        {
            var request = new DataTableRequest(this, sortOrder, search, pageIndex, pageSize);

            var vms = _departmentManager.GetAllByRequest(request);

            return View(vms);
        }

        public ActionResult Edit(int? id)
        {
            var vm = _departmentManager.Get(id);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DepartmentViewModel vm)
        {
            if (ModelState.IsValid)
            {
                _departmentManager.Save(vm);
                return RedirectToAction("Index");
            }

            return View(vm);
        }

        public ActionResult Delete(int id)
        {
            var vm = _departmentManager.Get(id);

            return View(vm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _departmentManager.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

DotNetFlicks.Web/Controllers/GenreController.cs
using DotNetFlicks.Common.Models;
using DotNetFlicks.Managers.Interfaces;
using DotNetFlicks.ViewModels.Genre;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DotNetFlicks.Web.Controllers
{
    [Authorize]
    public class GenreController : Controller
    {
        private IGenreManager _genreManager;

        public GenreController(IGenreManager genreManager)
        {
            _genreManager = genreManager;
        }

        public ActionResult Index(string sortOrder, string search, int? pageIndex, int? pageSize)
        {
            var request = new DataTableRequest(this, sortOrder, search, pageIndex, pageSize);

            var vms = _genreManager.GetAllByRequest(request);

            return View(vms);
        }

        public ActionResult View(int id)
        {
            var vm = _genreManager.Get(id);

            return View(vm);
        }

        public ActionResult Edit(int? id)
        {
            var vm = _genreManager.Get(id);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GenreViewModel vm)
        {
            if (ModelState.IsValid)
            {
                _genreManager.Save(vm);
                return RedirectToAction("Index");
            }

            return View(vm);
        }

        public ActionResult Delete(int id)
        {
            var vm = _genreManager.Get(id);

            return View(vm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _genreManager.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

DotNetFlicks.Web/Controllers/MovieController.cs
using DotNetFlicks.Common.Models;
using DotNetFlicks.Managers.Interfaces;
using DotNetFlicks.ViewModels.Movie;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DotNetFlicks.Common.Utilities;

namespace DotNetFlicks.Web.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        private IAccountManager _accountManager;
        private IMovieManager _movieManager;

        public MovieController(IAccountManager accountManager,
            IMovieManager movieManager)
        {
            _accountManager = accountManager;
            _movieManager = movieManager;
        }

        #region Client
        public ActionResult ViewAll()
        {
            var vm = _movieManager.GetAll();

            return View(vm);
        }

        public ActionResult ViewAllForUser()
        {
            var user = _accountManager.GetApplicationUser(HttpContext.User).Result;

            var vm = _movieManager.GetAllForUser(user.Id);

            return View(vm);
        }

        public ActionResult View(int id)
        {
            var user = _accountManager.GetApplicationUser(HttpContext.User).Result;

            var vm = _movieManager.Get(id, user.Id);

            return View(vm);
        }

        public ActionResult Purchase(int id)
        {
            var user = _accountManager.GetApplicationUser(HttpContext.User).Result;

            _movieManager.Purchase(id, user.Id);

            return RedirectToAction("View", new { id });
        }

        public ActionResult Rent(int id)
        {
            var user = _accountManager.GetApplicationUser(HttpContext.User).Result;

            _movieManager.Rent(id, user.Id);

            return RedirectToAction("View", new { id });
        }
        #endregion

        #region Administrator
        public ActionResult Index(string sortOrder, string search, int? pageIndex, int? pageSize)
        {
            var user = _accountManager.GetApplicationUser(HttpContext.User).Result;
            var request = new DataTableRequest(this, sortOrder, search, pageIndex, pageSize, user.Id);

            var vms = _movieManager.GetAllByRequest(request);

            return View(vms);
        }

        public ActionResult Edit(int? id)
        {
            var vm = _movieManager.GetForEditing(id);

            return View(vm);
        }

        /*Sprinkle on some CSRF
         *[ValidateAntiForgeryToken]
        */
        [HttpPost]
        public ActionResult Edit(EditMovieViewModel vm)
        {
            if (ModelState.IsValid)
            {
                //Check if the image exists, if not remove it.
                if (!WebUtility.URLExists(vm.ImageUrl)) {
                    vm.ImageUrl = "";
                }
                _movieManager.Save(vm);
                return RedirectToAction("Index");
            }

            return View(vm);
        }

        public ActionResult Delete(int id)
        {
            var user = _accountManager.GetApplicationUser(HttpContext.User).Result;

            var vm = _movieManager.Get(id, user.Id);

            return View(vm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _movieManager.Delete(id);

            return RedirectToAction("Index");
        }

        public ActionResult AddCastMember(int index)
        {
            var vm = new CastMemberViewModel { Index = index, Order = index };

            ViewData.TemplateInfo.HtmlFieldPrefix = string.Format("Cast[{0}]", index);

            return PartialView("../Movie/EditorTemplates/CastMemberViewModel", vm);
        }

        public ActionResult AddCrewMember(int index)
        {
            var vm = new CrewMemberViewModel { Index = index };

            ViewData.TemplateInfo.HtmlFieldPrefix = string.Format("Crew[{0}]", index);

            return PartialView("../Movie/EditorTemplates/CrewMemberViewModel", vm);
        }

        public string GetPersonSelectData(string query)
        {
            return _movieManager.GetPersonSelectData(query);
        }

        public string GetDepartmentSelectData(string query)
        {
            return _movieManager.GetDepartmentSelectData(query);
        }
        #endregion
    }
}

DotNetFlicks.Web/Controllers/PersonController.cs
using DotNetFlicks.Common.Models;
using DotNetFlicks.Managers.Interfaces;
using DotNetFlicks.ViewModels.Person;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DotNetFlicks.Web.Controllers
{
    [Authorize]
    public class PersonController : Controller
    {
        private IPersonManager _personManager;

        public PersonController(IPersonManager personManager)
        {
            _personManager = personManager;
        }

        public ActionResult Index(string sortOrder, string search, int? pageIndex, int? pageSize)
        {
            var request = new DataTableRequest(this, sortOrder, search, pageIndex, pageSize);

            var vms = _personManager.GetAllByRequest(request);

            return View(vms);
        }

        public ActionResult View(int id)
        {
            var vm = _personManager.Get(id);

            return View(vm);
        }

        public ActionResult Edit(int? id)
        {
            var vm = _personManager.Get(id);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PersonViewModel vm)
        {
            if (ModelState.IsValid)
            {
                _personManager.Save(vm);
                return RedirectToAction("Index");
            }

            return View(vm);
        }

        public ActionResult Delete(int id)
        {
            var vm = _personManager.Get(id);

            return View(vm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _personManager.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

DotNetFlicks.Web/Views/Shared/_DataTableTitle.cshtml
@model DotNetFlicks.ViewModels.Shared.DataTableViewModel

@if (Model.FilteredCount == Model.TotalCount)
{
    <h1>@ViewData["Title"] <small>(@Model.FilteredCount)</small></h1>
}
else
{
    <h1>@ViewData["Title"] <small>(@Model.FilteredCount of @Model.TotalCount)</small></h1>
}

DotNetFlicks.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotNetFlicks</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-select/css/bootstrap-select.css">
        <link rel="stylesheet" href="~/lib/ajax-bootstrap-select/css/ajax-bootstrap-select.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.0/css/bootstrap-select.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ajax-bootstrap-select/1.4.3/css/ajax-bootstrap-select.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/lib/bootstrap-select/js/bootstrap-select.js"></script>
        <script src="~/lib/ajax-bootstrap-select/js/ajax-bootstrap-select.js"></script>
        <script src="~/lib/font-awesome/js/fontawesome-all.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/tinysort/tinysort.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.0/js/bootstrap-select.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ajax-bootstrap-select/1.4.3/js/ajax-bootstrap-select.min.js"></script>
        <script src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validate/jquery.validate.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.9/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tinysort/2.3.6/tinysort.min.js"
                asp-fallback-src="~/lib/tinysort/tinysort.min.js"
                asp-fallback-test="window.tinysort">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand mb-0 h1">.NetFlicks</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar-content" role="tablist">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a asp-controller="Movie" asp-action="ViewAll" class="nav-link">Browse Movies</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Movie" asp-action="ViewAllForUser" class="nav-link">My Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Admin Settings</a>
                            <div class="dropdown-menu">
                                <a asp-controller="Movie" asp-action="Index" class="dropdown-item">Movies</a>
                                <a asp-controller="Person" asp-action="Index" class="dropdown-item">People</a>
                                <a asp-controller="Genre" asp-action="Index" class="dropdown-item">Genres</a>
                                <a asp-controller="Department" asp-action="Index" class="dropdown-item">Departments</a>
                            </div>
                        </li>
                    </ul>
                }
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <div class="container body-content">
        <br /><br />
        @RenderBody()
    </div>

    <br />

    <footer class="footer">
        <div class="container">
            <div class="d-flex">
                <span>&copy; @DateTime.Now.Year - .NetFlicks</span>
                <img class="ml-auto my-auto" src="~/images/powered-by-tmdb.png" height="40" alt="Powered by TMDB" />
            </div>
        </div>
    </footer>
</body>
</html>

DotNetFlicks.Web/Views/Shared/_MovieCardList.cshtml
@using DotNetFlicks.Common.Utilities

@model List<DotNetFlicks.ViewModels.Movie.MovieViewModel>

<div class="mx-auto d-flex flex-wrap justify-content-center justify-content-lg-start" style="max-width: 1088px;">
    @foreach (var movie in Model)
    {
        <div class="card movie-card m-3"
             style="width: 15rem;"
             data-name="@movie.Name"
             data-date="@(((DateTimeOffset)movie.ReleaseDate).ToUnixTimeSeconds().ToString())"
             data-price="@movie.RentCost"
             data-purchase-date="@movie.PurchaseDateString">
            <a asp-controller="Movie" asp-action="View" asp-route-id="@movie.Id" style="color: black; text-decoration: none;">
                <img class="card-img-top" src="@movie.ImageUrl">
                <div class="card-body" style="padding-bottom: 0; height: 44px;">
                    @if (movie.Name.Count() > 20)
                    {
                        <h6 class="card-title mb-0">@movie.Name</h6>
                    }
                    else
                    {
                        <h5 class="card-title mb-0">@movie.Name</h5>
                    }
                </div>
                <div class="card-footer text-muted" style="background: none; border-top: none;">
                    <div class="d-flex">
                        <p class="card-text mb-0"><small>@movie.ReleaseDate.ToCustomDateString()</small></p>
                        @if (!(bool)ViewData["OnlyPurchasedMovies"])
                        {
                            <p class="card-text ml-auto mb-0">$@movie.RentCost</p>
                        }
                    </div>
                </div>
            </a>
        </div>
    }
</div>

DotNetFlicks.Web/Views/Shared/_MovieSorter.cshtml
<h5 class="my-auto mr-2">Sort By</h5>
<div class="dropdown my-auto movie-sorter">
    @if ((bool)ViewData["OnlyPurchasedMovies"])
    {
        <button class="btn btn-primary dropdown-toggle" type="button" id="sort-movies-dropdown" data-toggle="dropdown">Purchase Date</button>

        <div class="dropdown-menu">
            <a class="dropdown-item sort-movies active text-white" id="data-purchase-date">Purchase Date</a>
            <a class="dropdown-item sort-movies" id="data-date">Release Date</a>
            <a class="dropdown-item sort-movies" id="data-name">Name</a>
        </div>
    }
    else
    {
        <button class="btn btn-primary dropdown-toggle" type="button" id="sort-movies-dropdown" data-toggle="dropdown">Release Date</button>

        <div class="dropdown-menu">
            <a class="dropdown-item sort-movies active text-white" id="data-date">Release Date</a>
            <a class="dropdown-item sort-movies" id="data-price">Price</a>
            <a class="dropdown-item sort-movies" id="data-name">Name</a>
        </div>
    }

    <button class="btn btn-primary" id="sort-direction" data-sort="desc" type="button"><i class="fas fa-arrow-down"></i></button>
</div>

DotNetFlicks.Web/Views/Shared/_PaginationToolbar.cshtml
@model DotNetFlicks.ViewModels.Shared.DataTableViewModel

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div class="d-flex justify-content-end mt-4 pagination-toolbar">
    @if (Model.FilteredCount == Model.TotalCount)
    {
        <p class="my-auto mr-auto">@Model.FirstItemIndex - @Model.LastItemIndex of @Model.FilteredCount items</p>
    }
    else
    {
        <p class="my-auto mr-auto">@Model.FirstItemIndex - @Model.LastItemIndex of @Model.FilteredCount items (filtered from @Model.TotalCount total items)</p>
    }

    <div class="btn-group btn-group-toggle my-auto">
        <!-- Display link to previous page -->
        <a asp-action="Index"
           asp-route-sortOrder="@Model.SortOrder"
           asp-route-search="@Model.Search"
           asp-route-pageIndex="@(Model.PageIndex - 1)"
           asp-route-pageSize="@Model.PageSize"
           class="btn btn-outline-primary @prevDisabled">
            <i class="fas fa-chevron-left my-auto ml-auto"></i>
        </a>

        @for (var i = 1; i <= Model.PageCount; i++)
        {
            //Display page links for the current page, the pages on both sides of the current page, the first page and last page
            if (Math.Abs(Model.PageIndex - i) < 2 || i == 1 || i == Model.PageCount)
            {
                <a asp-action="Index"
                   asp-route-sortOrder="@Model.SortOrder"
                   asp-route-search="@Model.Search"
                   asp-route-pageIndex="@i"
                   asp-route-pageSize="@Model.PageSize"
                   class="btn btn-outline-primary d-none d-md-inline @(i == Model.PageIndex ? "active" : "")">
                    @i
                </a>
            }
            //Display "..." spacers to represent page number skips between the middle 3 pages and the first and last pages
            else if (Math.Abs(Model.PageIndex - i) < 3)
            {
                <a class="btn btn-outline-primary d-none d-md-inline disabled">...</a>
            }
        }

        <!-- Display link to next page -->
        <a asp-action="Index"
           asp-route-sortOrder="@Model.SortOrder"
           asp-route-search="@Model.Search"
           asp-route-pageIndex="@(Model.PageIndex + 1)"
           asp-route-pageSize="@Model.PageSize"
           class="btn btn-outline-primary @nextDisabled">
            <i class="fas fa-chevron-right my-auto ml-auto"></i>
        </a>
    </div>
</div>

DotNetFlicks.Web/Views/Shared/_SearchToolbar.cshtml
@model DotNetFlicks.ViewModels.Shared.DataTableViewModel

<form asp-action="Index" method="get">
    <input type="hidden" name="SortOrder" value="@Model.SortOrder" />

    <div class="d-flex mb-4">
        <div>
            <p class="d-none d-sm-inline-block mr-2">Items per page: </p>
            <select class="d-inline-block form-control w-auto" asp-items="Model.PageSizeOptions" name="PageSize" onchange="this.form.submit();"></select>
        </div>

        <div class="ml-auto">
            <div class="input-group mb-3">
                <input type="text" class="form-control" name="Search" value="@Model.Search" placeholder="Search" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>

        @if (!string.IsNullOrEmpty(Model.Search))
        {
            <div class="ml-3 mt-2">
                <a asp-action="Index" asp-route-sortOrder="@Model.SortOrder" asp-route-pageSize="@Model.PageSize">Clear search</a>
            </div>
        }
    </div>
</form>

DotNetFlicks.Web/Views/Shared/_SortableHeader.cshtml
@model DotNetFlicks.ViewModels.Shared.SortableHeaderViewModel

@{ 
    var ascSort = Model.ColumnName + "_Asc";
    var descSort = Model.ColumnName + "_Desc";
    var newSortOrderOnClick = Model.DataTable.SortOrder == ascSort ? descSort : ascSort;
}

<a class="d-block p-3"
   asp-action="Index"
   asp-route-sortOrder="@newSortOrderOnClick"
   asp-route-search="@Model.DataTable.Search"
   asp-route-pageIndex="@Model.DataTable.PageIndex"
   asp-route-pageSize="@Model.DataTable.PageSize">
    <div class="d-flex">
        <h5 class="mb-1">@Model.ColumnName</h5>
        @if (Model.DataTable.SortOrder == ascSort)
        {
            <i class="fas fa-sort-up my-auto ml-auto"></i>
        }
        else if (Model.DataTable.SortOrder == descSort)
        {
            <i class="fas fa-sort-down my-auto ml-auto"></i>
        }
        else
        {
            <i class="fas fa-sort my-auto ml-auto" style="color: lightgray;"></i>
        }
    </div>
</a>